#don't change key 'version' if you can't edit this plugin
Version: "0.1"
#These keys are default, you can change them
JoinServerMessage1: "Welcome to this Server"
JoinServerMessage2: "Use '/shout' to show your text in the server all worlds."
UseShoutCommandLogger: "A player shouting"
UseShoutsetCommandLogger: "A op setting config"
#These are prices of shouting about players, you need ready for EconomyAPI as the dependence plugin
ChoseMoodPrice: 100
ChoseColorPrice: 100
SendTextPrice: 100
#You can decide whether to call in the current world or in the whole server(use "server and world")
ShoutMode: "server"
#Shout Ui text, you can change them
ShoutSetUITitle: "Shoutset Page"
ShoutSetInformation: "Please enter ChoseMoodPrice,ChoseColorPrice,SendTextPrice in order in the three input boxes!Please enter an integer"
ShoutTitle: "[Shout]"
ShoutUITitle: "Shout Page"
ShoutMoodTitle: "You shouting chose Mood need Money:§e"
ShoutColorTitle: "You shouting chose Colorful need Money:§e"
ShoutInputTitle: "You shouting text be sended need Money:§e"
ShoutModeTitle: "You shouting mode(a way of showing your text)"
#Shout result, you can change them
ShoutSuccess: "Shouted Successfully! Costed money:§e"
ShoutFail: "Shouted Failingly! No expense incurred."

